### ISSUE TITLE
[Question or Bug] Encoding / decoding (RFC3986)

### ISSUE THREAD

**Issue by Gounlaf** [thephpleague/uri-components#28]
|    Q        |   A
|------------ | ------
| Version     | 6.0.1

### Question

Hi,

As part of RFC3986, current implementation does encode specials characters in components.
But, I expected it **decode** them when decomposing / access to some components. Unfortunately, it does not.

```php
$uri = Uri::createFromString('http://example.com/path/to?q=foo%20bar#section-42')
    ->withUserInfo('user', "'O=+9zLZ}%{z+:tC");

$userInfo = UserInfo::createFromUri($uri);

var_dump($userInfo->getPass());
// expected: string(16) "'O=+9zLZ}%{z+:tC"
// actual: string(18) "'O=+9zLZ}%25{z+:tC"
```

So, Is it intended, and I must decode (via `rawurlencode`) user/pass (and any other parameters I want), or is it a bug?

Thanks,

Regards.

**Comment by nyamsprod** [comment]
@Gounlaf I've looked into your report and I'm undecided on how to tackle your question. In one hand you are expecting a fully decoded component in the other hand the class does everything to keep interop and to not mangle with the received data. The result is the status quo we have now 😢 

to improve interop it is better to always have `%` encoded as `%25` because it is a reserved character with a meaning.

If I decode everything without care then I end up with using `rawurlencode` which would resolve your issue but mangle and then return some errors in some other instance. TL;DR to be more conservative I prefer to only decode safe character and `%25` is not safe. 

So I'd say that it is a case where some business logic should/do need to intervene in a case by case rule 🤔 

I don't know if what I'm saying makes sense for you ?

**Comment by Gounlaf** [comment]
Hi @nyamsprod,

Thanks for you answers.
I understand what your are saying, but I'm not really convinced :sweat_smile:.

If some underlying library/framework/whatever use uri-components to transport/manipulate some data, I expect to have my "uri components" untouched when I get it back; if from a point of my application I put some user:password and I can't get it back as it somewhere else... it's strange =/

IMO, after reading RFC again, I understand/think that everything should be encoded/decoded by the components/manipulators; encoding should only be done at a "final stage", when converting Uri to string; and decoding should be done only when parsing string and convert it to components/part of the Uri.

**Comment by nyamsprod** [comment]
@Gounlaf indeed the components should encode/decode but the difficulty is that you need to avoid double encoding and full decoding otherwise you end up in the situation of the query string whose decoding from PHP differs greatly from the one done by Javascript because of full decoding occurring on PHP side. 

So again I'll see what I can do to fix this but is must be done correctly otherwise you introduce unforseen bugs.

**Comment by Gounlaf** [comment]
I understand :wink: . Hope you will find a "solution" .
If not, I will make a workaround in my apps, knowing this specificity.

**Comment by nyamsprod** [comment]
I've merged the patch hopefully if I have time I'll release a patch later this week

**Comment by Gounlaf** [comment]
Thanks again!
