### ISSUE TITLE
Maybe we should use Query::getContent() instead of Query::__toString in UriModifier?

### ISSUE THREAD

**Issue by brentybh** [thephpleague/uri-components#31]
|    Q        |   A
|------------ | ------
| Version     | 2.0.1

### Question

https://github.com/thephpleague/uri-components/blob/0f1568baca257418ae2419205e9472a41d944c40/src/UriModifier.php#L75

For example, when try to remove query pair that doesn't exist:

```
$uri = Uri::createFromString('https://example.com/');
echo UriModifier::removePairs($uri, 'test')->__toString(); // Output: https://example.com/?
echo $uri->withQuery(Query::createFromUri($uri)->withoutPair('test')->getContent());
// Output: https://example.com/
```

That's because, the __toString method will convert null to empty string, but when building URI string, if the query is empty string the output will be `?`, if the query is null the output will be empty string.

I personally think adding a useless "?" at the end of URI is not so good.
So maybe we should use Query::getContent() instead of Query::__toString in UriModifier?

**Comment by nyamsprod** [comment]
@brentybh thanks for using the library.

I see where you are coming with this suggestion but we can not just switch between methods because the modifier *MUST* be usable with PSR-7 UriInterface and the League own UriInterface.

What we can do is something along these lines

```php
<?php

public static function removePairs($uri, string ...$keys)
{
    $query = Query::createFromUri($uri)->withoutPair(...$keys);
    if ($uri instanceOf \Psr\Http\Message\UriInterface) {
        return $uri->withQuery($query->__toString());
    }

    return $uri->withQuery($query->getContent()); 
}
```

What do you think ... the same re-write should then be applied on all query related modifier 🤔

**Comment by brentybh** [comment]
Thank you.
